all: yaps.dll yaps_sync.dll
	# Comment here preserves the prior tab
yaps.dll: yaps.cpp
	Rscript --vanilla -e "TMB::compile('yaps.cpp', '-O1 -g',DLLFLAGS='')"
yaps_sync.dll: yaps_sync.cpp
	Rscript --vanilla -e "TMB::compile('yaps_sync.cpp', '-O1 -g',DLLFLAGS='')"

clean:
	rm -rf *.dll
	